Update README.md
COSC3020/theoretical-sorting-Dorian-Scholz pull request #3
Opened 2024-12-10 06:33 UTC by Dorian-Scholz

2024-12-10 16:48 UTC, larskotthoff requested changes
Plagiarism note missing.

2024-12-11 03:42 UTC, Dorian-Scholz commented
What?

2024-12-11 03:52 UTC, Dorian-Scholz commented
What does this mean?

2024-12-11 17:40 UTC, larskotthoff commented
The plagiarism note you need to insert into all submissions. See first lecture, slides, syllabus.

2024-12-11 18:07 UTC, closed without merging